services:
  traefik:
    image: traefik:v2.9
    command:
      - --api.insecure=false
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Configure Let's Encrypt
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=al.termure@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-lets-encrypt:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  web:
    image: jackjakarta/klikr:${TAG_VERSION}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.fastapi-app.rule=Host(`klikr.app`)'
        - 'traefik.http.routers.fastapi-app.entrypoints=websecure'
        - 'traefik.http.routers.fastapi-app.tls.certresolver=myresolver'
        - 'traefik.http.services.fastapi-app.loadbalancer.server.port=3000'

volumes:
  traefik-lets-encrypt:
