name: Build and Deploy Production

on:
  push:
    tags:
      - '1.*.*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Set up Docker image tags
        id: vars
        run: |
          echo "TAG_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build and push to docker hub
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/jack/link-shortner
            git pull
            chmod +x fetch-env.sh && ./fetch-env.sh prod && \
            echo "TAG_VERSION=${{ env.TAG_VERSION }}" >> .env && \
            docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/klikr:${{ env.TAG_VERSION }} . && \
            docker push ${{ secrets.DOCKER_USERNAME }}/klikr:${{ env.TAG_VERSION }}

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/jack/link-shortner
            export $(grep -v '^#' .env | xargs) && \
            envsubst < docker-compose.production.yml | docker stack deploy -c - klikr && \
            docker system prune -f
