name: Checks

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  checks:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install PNPM
        run: corepack enable && corepack prepare

      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm format:check
      - name: Check types
        run: pnpm types
      - name: Check linter
        run: pnpm lint
      - name: Unit tests
        run: pnpm test
